export const mockJobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "Công ty ABC",
    location: "Hà Nội",
    type: "Full-time",
    salary: "20 - 30 triệu",
    description: "Tham gia phát triển giao diện người dùng cho các dự án web.",
    requirements: ["ReactJS", "HTML/CSS", "Git"],
    benefits: ["Lương thưởng hấp dẫn", "Bảo hiểm đầy đủ"],
    postedDate: "2025-06-20",
    deadline: "2025-07-20",
    status: "active",
  },
  {
    id: 2,
    title: "Backend Developer",
    company: "Công ty XYZ",
    location: "TP. HCM",
    type: "Part-time",
    salary: "15 - 25 triệu",
    description: "Phát triển và duy trì hệ thống API.",
    requirements: ["Node.js", "MySQL", "RESTful API"],
    benefits: ["Làm việc hybrid", "Du lịch công ty"],
    postedDate: "2025-06-22",
    deadline: "2025-07-22",
    status: "active",
  },
  {
    id: 3,
    title: "UI/UX Designer",
    company: "Creative Studio",
    location: "Đà Nẵng",
    type: "Remote",
    salary: "10 - 20 triệu",
    description: "Thiết kế giao diện và trải nghiệm người dùng.",
    requirements: ["Figma", "Prototype", "User Research"],
    benefits: ["Linh hoạt thời gian", "Thưởng cuối năm"],
    postedDate: "2025-06-25",
    deadline: "2025-07-25",
    status: "active",
  },
  {
    id: 4,
    title: "Mobile App Developer",
    company: "TechNext",
    location: "Cần Thơ",
    type: "Full-time",
    salary: "18 - 28 triệu",
    description: "Phát triển ứng dụng mobile trên nền tảng React Native.",
    requirements: ["React Native", "Redux", "API Integration"],
    benefits: ["Laptop riêng", "Bonus hiệu suất"],
    postedDate: "2025-06-18",
    deadline: "2025-07-18",
    status: "active",
  },
  {
    id: 5,
    title: "QA/QC Tester",
    company: "VinaSoft",
    location: "Hải Phòng",
    type: "Full-time",
    salary: "12 - 18 triệu",
    description: "Thực hiện kiểm thử phần mềm, viết test case, report bug.",
    requirements: ["Manual Testing", "JIRA", "API Testing"],
    benefits: ["Đào tạo nâng cao", "Bảo hiểm mở rộng"],
    postedDate: "2025-06-15",
    deadline: "2025-07-15",
    status: "active",
  },
  {
    id: 6,
    title: "System Administrator",
    company: "Global IT",
    location: "Hồ Chí Minh",
    type: "On-site",
    salary: "22 - 32 triệu",
    description: "Quản trị hệ thống server, xử lý sự cố mạng và bảo mật.",
    requirements: ["Linux", "Docker", "CI/CD"],
    benefits: ["Thưởng quý", "Khóa học miễn phí"],
    postedDate: "2025-06-10",
    deadline: "2025-07-10",
    status: "active",
  },
];
